name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Verificar Local
        run: |
          pwd
          ls

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: python -m unittest discover -s .

  # docker-build:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Build Docker image
  #       run: docker build -t lab-api .

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: docker-build
  #   steps:
  #     - name: Deploy to Vercel
  #       run: |
  #         npm i -g vercel
  #         vercel --prod --token ${{ secrets.VERCEL_TOKEN }}